version: '3.8'

services:
  backend:
    build:
      context: ./server  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile  
    ports:
      - "5173:5173" 
    depends_on:
      - backend
